apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: redis-storage
  hostPath:
    path: /tmp/k8s-redis-data # path inside Kind node
