services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: seiri-server
    ports:
      - "3004:3000" 
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_NAME: thot
      CACHE_HOST: redis
      CACHE_PORT: 6379
      PORT: 3000
      TOKEN_SECRET: secret
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
      target: development
    image: seiri-web
    ports:
      - "3005:3000" 
    environment:
      REACT_APP_API_URL: http://localhost:3004/api/
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: thot
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  pg-data:
  
