services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    image: seiri-server
    container_name: server
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  client:
    build: ./client
    image: seiri-web
    container_name: client
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  
