version: "3.9"

services:
  server:
    build: ./server
    image: seiri-server
    container_name: seiri-server
    depends_on:
      - db
    ports:
      - "3004:3000"
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: marius
      DB_PASSWORD: root
      DB_NAME: thot

  web:
    build: ./web
    image: seiri-web
    container_name: seiri-web
    environment:
      SERVER_API_URL: http://server:3000/
    depends_on:
      - server
    ports:
      - "3005:3000"
    restart: always

  db:
    image: mysql:5.7.41
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: thot
      MYSQL_USER: marius
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306" 
    volumes:
      - mysql-data:/var/lib/mysql
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  mysql-data:
