#!/bin/bash

# Script to fix the migration issue and run tracking migrations

echo "=== Fixing Migration Issue ==="
echo ""
echo "Option 1: Manually mark the migration as executed"
echo "Run this SQL in your database:"
echo ""
echo "INSERT INTO migrations (\`timestamp\`, \`name\`) VALUES (1728648707885, 'AddIsFanInNoteTable1728648707885');"
echo ""
echo "Then run: npm run migration:run"
echo ""
echo "---"
echo ""
echo "Option 2: If running in Docker, execute migrations in the container:"
echo ""
echo "docker-compose exec server npm run migration:run"
echo ""
echo "---"
echo ""
echo "Option 3: Delete the problematic migration file (if column already exists):"
echo ""
echo "rm src/db/migrations/1728648707885-AddIsFanInNoteTable.ts"
echo "npm run build"
echo "npm run migration:run"
echo ""
echo "=== After fixing, the following tracking migrations will run: ==="
echo "1. CreateTrackingTable1739227000000 - Creates tracking and tracking_history tables"
echo "2. AddProjectIdToTracking1739227654000 - Adds optional project relationship"
