export const projects = [
  {
    id: 1,
    name: "2023 Roadmap",
    notes: [],
    tasks: [],
    description: "",
    isArchive: false,
    color: "yellow",
  },
  {
    id: 2,
    name: "2022",
    notes: [],
    tasks: [],
    description: "",
    isArchive: false,
    color: "teal",
  },
  {
    id: 3,
    name: "Bills",
    notes: [],
    tasks: [],
    description: "",
    isArchive: false,
    color: "green",
  },
  {
    id: 4,
    name: "Groceries",
    notes: [],
    tasks: [],
    description: "",
    isArchive: false,
    color: "grape",
  },
  {
    id: 5,
    name: "Work",
    notes: [],
    tasks: [],
    description: "",
    isArchive: false,
    color: "blue",
  },
];
