apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: seiri-server:4.2
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "npm run migration:run"]
          env:
            - name: DB_HOST
              value: db-service
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres-database
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-password
