apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: seiri-backend
          image: seiri-server:4.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: TOKEN_SECRET
              value: secret
            - name: PORT
              value: "3000"
            - name: CACHE_HOST
              value: redis-service
            - name: CACHE_PORT
              value: "6379"
            - name: DB_HOST
              value: db-service
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres-database
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres-password
