name: client-ci

on:
  pull_request:
    branches:
      - main
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image and Run Test
        working-directory: ./client
        run: docker build --target prod  -t test-image .
