name: server ci/cd

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs: 
  build: 
    runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2