name: server

on:
  push:
    branches:
      - 34-setup-a-cicd-pipeline
    paths:
      - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"
          cache-dependency-path: "server/npm-shrinkwrap.json"

      - name: Build Docker image and Run Test
        working-directory: ./server
        run: |
          docker build . -t server
          docker run --rm server npm run test
