name: web

on:
  push:
    branches:
      - main
    paths:
      - "web/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Build Docker image and Run Test
        working-directory: ./web
        run: |
          docker build . -t web
          docker run --rm web npm run test
